# More config examples could be found here - https://github.com/commit-check/commit-check/blob/main/.commit-check.yml
checks:
  - check: message
    regex: '(\([\w\-\.]+\))?([\w ])+([\s\S]*)'
    error: "The commit message should be structured as follows:\n
    <commit header>\n\n
    <commit body>"
    suggest: Please check your commit message whether matches above regex
