name: Validate commit messages

on: [pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate PR commit with commitlint
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.yml
