name: Commit check

on: [push, pull_request]

jobs:
  commit-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run commit msg check
      env:
        GH_TOKEN: ${{ github.token }}
      uses: commit-check/commit-check-action@v0.9.2
      with:
        message: true
        branch: false
        author-name: true
        author-email: true
        commit-signoff: true
        merge-base: false
        imperative: false
        job-summary: true
        pr-comments: false
